apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airbyte-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: minikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airbyte-webapp
                port:
                  number: 8080
